### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [ccolon86/prj-rev-bwfs-dasmoto#2]
You could use comma-separated selectors to specify shared properties for multiple elements:

```css
h1, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/ccolon86/prj-rev-bwfs-dasmoto/blob/master/Dasmatos%20Arts%20and%20Crafts/Dasmotos.css
